version: '3.9'
services:
  db:
    image: postgres:14.9
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: skewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - skewer-network
  skewer:
    image: hiagolaurenco/skewer
    restart: always
    build: ./skewer
    working_dir: /skewer
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/skewer
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 123456
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - skewer-network

networks:
  skewer-network:
    driver: bridge