server:
    port: 8080
file:
     upload-dir: /home/runner/work/skewer/UploadDir
#    upload-dir: /home/runner/work/skewer/skewer/skewer/UploadDir
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/skewer
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        generate-ddl: true
    # Logger configuration
    logging:
        pattern:
            console: "%d %-5level %logger : %msg%n"
        level:
            org.springframework: info
            org.hibernate: debug

