name: Continuos Integration with Github Actions

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: /home/runner/work/skewer/skewer
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: /home/runner/work/
      run: |
         sudo snap remove docker
         sudo apt install docker.io docker-compose
         docker-compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/skewer:latest ${{ secrets.DOCKER_USERNAME }}/skewer:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/skewer:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/skewer:latest

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
